### ISSUE TITLE
请教下你的建筑物的生成计算方式是怎么算的？

### ISSUE THREAD

**Issue by GitCod-Man** [wayperwayp/FlappyBirdCocos#1]
请教下你的建筑物与相机位置的生成计算方式是怎么算的？

**Comment by jamescasia** [comment]
`if(Math.round(this.camera.x % 200 ) <=1   ){ 
            this.pctr+=1; 
            var randPos =  320*cc.random0To1();
            this.spawnPipe( randPos);
            this.spawnBotPipe( randPos); 
        }`

so what this does is that every 200 units the camera moves, it spawns a new pipe at a random height. The same thing is also done for the ground

**Comment by GitCod-Man** [comment]
the ground code: 
 if(Math.round(this.camera.x % 700) <= 4 ){  //  why  % 700   ? and  <= 4 ?
            this.ctr+=1;
		
            this.spawnGround(); 
        }


the method: spawnGround() {
 newGround.setPosition( this.ctr*705 , 0)  // why  705 ？？　
ｓｏ　ｉ could not understant  the number  ,please.

**Comment by jamescasia** [comment]
Each ground object is 705 units away from each other

**Comment by GitCod-Man** [comment]
![image](https://user-images.githubusercontent.com/16233416/47889059-01f95680-de83-11e8-96a1-6371ec135d6f.png)
Is that what you mean?  There is a gap between the two floors.

**Comment by jamescasia** [comment]
The anchor of a ground is located at the top right part, that is where position is measured for the object
![image](https://user-images.githubusercontent.com/29967444/47889263-07a36c00-de84-11e8-84d0-c1570e7ce827.png)

**Comment by GitCod-Man** [comment]
em.......   buy  your ground image size is  x: 168

**Comment by jamescasia** [comment]
Well, I think because the game engine uses a different measurement system.
